/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KategorieIndexRouteImport } from './routes/kategorie/index'
import { Route as ProduktyIndexRouteImport } from './routes/produkty/index'
import { Route as ProduktySlugRouteImport } from './routes/produkty/$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorieIndexRoute = KategorieIndexRouteImport.update({
  id: '/kategorie/',
  path: '/kategorie/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktyIndexRoute = ProduktyIndexRouteImport.update({
  id: '/produkty/',
  path: '/produkty/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktySlugRoute = ProduktySlugRouteImport.update({
  id: '/produkty/$slug',
  path: '/produkty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produkty/$slug': typeof ProduktySlugRoute
  '/kategorie/': typeof KategorieIndexRoute
  '/produkty/': typeof ProduktyIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produkty/$slug': typeof ProduktySlugRoute
  '/kategorie': typeof KategorieIndexRoute
  '/produkty': typeof ProduktyIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/produkty/$slug': typeof ProduktySlugRoute
  '/kategorie/': typeof KategorieIndexRoute
  '/produkty/': typeof ProduktyIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/produkty/$slug'
    | '/kategorie/'
    | '/produkty/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/produkty/$slug' | '/kategorie' | '/produkty' | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/produkty/$slug'
    | '/kategorie/'
    | '/produkty/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProduktySlugRoute: typeof ProduktySlugRoute
  KategorieIndexRoute: typeof KategorieIndexRoute
  ProduktyIndexRoute: typeof ProduktyIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorie/': {
      id: '/kategorie/'
      path: '/kategorie'
      fullPath: '/kategorie/'
      preLoaderRoute: typeof KategorieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty/': {
      id: '/produkty/'
      path: '/produkty'
      fullPath: '/produkty/'
      preLoaderRoute: typeof ProduktyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkty/$slug': {
      id: '/produkty/$slug'
      path: '/produkty/$slug'
      fullPath: '/produkty/$slug'
      preLoaderRoute: typeof ProduktySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProduktySlugRoute: ProduktySlugRoute,
  KategorieIndexRoute: KategorieIndexRoute,
  ProduktyIndexRoute: ProduktyIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
